provider:  
  name: deepseek  
  mode: http  
  base_url: https://api.deepseek.com  
  model: deepseek-chat  
  api_key: sk-c08f1194f00947a2b632821230666a83
  timeout_sec: 30
  max_retries: 2  
  temperature: 0.0  
  max_tokens: 300  
  top_p: 1.0  
  
service:  
  require_auth: false  
  return_vector: false 

# ASR队列配置
asr:
  # ASR转写结果队列目录 - 必须与同事的输出目录一致
  queue_dir: "outputs"
  
  # 服务器部署时的绝对路径配置（可选）
  # queue_dir: "/path/to/shared/outputs"
  
  # 监听间隔（秒）
  monitor_interval: 1.0
  
  # 历史记录保存数量
  max_history: 100
  
  # 是否自动启动队列监听
  auto_start: true
